# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


commands:
  ci_steps:
    parameters:
      platform:
        type: string
    steps:
      - checkout
      - run:
          name: Build
          command: make

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - checkout
      - run:
          name: Point Unit Testing
          command: 'make && cd build && ls -la && ls -la tests && ctest tests/td_test'
