# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:    
      - run:
          name: Installing SUDO
          command: 'apt update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt update && apt install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt install -y cmake'
      - run:
          name: Installing LCOV
          command: 'apt install -y lcov'
      - run:
          name: Installing CURL
          command: 'apt install -y curl'
      - checkout
      - run:
          name: Build & Test
          command: |
            make clean
            make unit_tests
            cd build
            make test
            make coverage
            bash <(curl -s https://codecov.io/bash) -f cmake_coverage.output

          
